### ISSUE TITLE
Unable to open certain PDF files using system viewer due to file names do not match the actual PDF filename

### ISSUE THREAD

**Issue by zhaokoh** [giovannicoppola/paperpAlfred#1]
Thank you for creating this amazing Alfred paperpile plugin. I noticed I am unable to open certain PDF files using system viewer, i.e. after searching for a paper, pressing "Enter" does not do anything.

After some debugging, I found out that the filename extracted from Alfred Workflow (i.e. the query response item 1) does not match the local file name.

The extracted file name from query response contains an additional space (or empty) character after " ...<space><space>"

So here is the extracted filename:

"Fleming et al. 2018 - Beyond the Trial - Systematic Review of Real-World ...  Digital Self-Help Interventions for Depression.pdf"

But my local file name is:

"Fleming et al. 2018 - Beyond the Trial - Systematic Review of Real-World ... Digital Self-Help Interventions for Depression, Low Mood, or Anxiety.pdf"

Notice the first file name contains double space characters after " ...".

At the moment, I did a workaround in the Alfred shell script (open PDF with system viewer) to replace the " ...  " with "*" wildcard:

escape_query=`echo "{query}" | sed -e "s/ ...  / \*/g"`
find "$PAPPATH" -name "$escape_query" |  head -n 1 | tr \\n \\0 | xargs -0 open

But would be much appreciated if the future release can incorporate this change?

**Comment by giovannicoppola** [comment]
Hi @zhaokoh, glad you find the workflow useful, and thanks for reporting this. I was able to reproduce it, however the extra space is present in the original JSON output and therefore seems an inconsistency in the Paperpile export. I estimate it affects 1.7% of the records in my library. 

Your workaround is valid and I can push a similar one in the workflow, however I tried to contact Paperpile first in case they are able to fix this on their end. I will keep you posted!

**Comment by zhaokoh** [comment]
Thanks @giovannicoppola. Yeah, I suspected it could be a problem upstream (i.e. paperpile). So if this can be fixed upstream, that will make it easier :).

**Comment by giovannicoppola** [comment]
@zhaokoh they will fix it at some point, but in the meantime I pushed a new version which should fix this particular problem. As I mentioned in my notes there seems to be no single logic in file naming and many edge cases, so please feel free to let me know if you notice anything broken!

**Comment by zhaokoh** [comment]
Thanks @giovannicoppola. Much appreciated.
