### ISSUE TITLE
Possibility of using bibtex file instead of JSON?

### ISSUE THREAD

**Issue by chenbinzero** [giovannicoppola/paperpAlfred#2]
Since paperpile can auto export library to a bibtex file, I wonder if it is possible to use bibtex as the database? This way the library is always up to date without the need to manually export JSON.
![image](https://user-images.githubusercontent.com/34108850/119227467-ff5fba80-badb-11eb-8364-abc2b285ac8b.png)

**Comment by giovannicoppola** [comment]
Thanks @chenbinzero that would be great, but the BibTeX export is missing a lot of fields needed for paperpAlfred to work (folders, labels, paperpile ID, google drive ID etc). so a version of the workflow based on BibTeX export would have fewer features ... but it is appealing to have a always-up-to-date database and it could be done if others are interested. Ideally paperpile will extend this feature to their JSON export.

**Comment by chenbinzero** [comment]
I agree, it would be cool if paperpile auto exports JSON!
