### ISSUE TITLE
Publicly sync-ed BibTex file?

### ISSUE THREAD

**Issue by beib** [giovannicoppola/paperpAlfred#3]
Currently some testing of Github automatic export/sync is available and working, would it be possible to have this Workflow point directly to a public Github repo with a sync-ed BibTeX file? Thank you for making this useful Workflow! :)

**Comment by giovannicoppola** [comment]
sorry I missed this comment! Unfortunately the BibTeX export is missing a lot of information needed for the workflow to work, I think automatic JSON export is on the roadmap and will be available at some point...
