### ISSUE TITLE
Library autoupdate

### ISSUE THREAD

**Issue by sihaog** [giovannicoppola/paperpAlfred#4]
As far as I understand, paperpAlfred requires manual update of JSON paperpile library and reset the PATH, which is not quite feasible for users.

**Comment by giovannicoppola** [comment]
yes, that would be great! Paperpile provides an auto-updating BibTeX, but that is missing a lot of useful information. 
I encourage you to propose an autoupdating JSON output to the Paperpile developers on their forum.
