### ISSUE TITLE
paperpAlfred not loading new entries in PAPLIBRARY

### ISSUE THREAD

**Issue by TarjinderSingh** [giovannicoppola/paperpAlfred#5]
I recently exported my Paperpile Library to a JSON format multiple times to update my list of papers. Despite this, none of my recent papers appear or are searchable in PaperpAlfred. While the plugin's functionality remains mostly intact, it fails to load any new files. I'm uncertain how to best approach debugging this issue.

**Comment by giovannicoppola** [comment]
Hi TJ! I hope you are well. I am honored you are using PaperpAlfred! It sounds like it's not pointing to the right file, have you checked the file path in Workflow configuration?

**Comment by giovannicoppola** [comment]
assuming this is resolved. @TarjinderSingh let me know if not.
